// <auto-generated />
using System;
using EmotionalIntelligenceTest.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmotionalIntelligenceTest.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20200229051539_five")]
    partial class five
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmotionalIntelligenceTest.Models.Answer", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnName("ID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnName("content")
                        .HasColumnType("text");

                    b.Property<int>("QuestionID")
                        .HasColumnName("QuestionID")
                        .HasColumnType("int");

                    b.Property<bool>("correct")
                        .HasColumnName("correct")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("QuestionID");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("EmotionalIntelligenceTest.Models.Question", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnName("ID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnName("content")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<byte[]>("image")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("EmotionalIntelligenceTest.Models.Answer", b =>
                {
                    b.HasOne("EmotionalIntelligenceTest.Models.Question", "Question")
                        .WithMany("Answer")
                        .HasForeignKey("QuestionID")
                        .HasConstraintName("FK_Answers_Questions")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
